let CATEGORIES=[];
const pages={dashboard:['Inicio','Organiza tus recursos de Sorprezz desde un solo lugar.'],new:['Nueva descarga','Pega un enlace, clasifícalo y descárgalo.'],library:['Biblioteca','Busca y administra todos los recursos registrados.'],categories:['Categorías','Crea la estructura que usarás para organizar los materiales.'],settings:['Configuración','Define dónde se guardarán los archivos.']};

async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||'Error en la operación');return data}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3500)}
function fmtBytes(n){n=Number(n||0);if(!n)return '0 B';const u=['B','KB','MB','GB','TB'];let i=Math.floor(Math.log(n)/Math.log(1024));return (n/Math.pow(1024,i)).toFixed(i?1:0)+' '+u[i]}
function statusLabel(s){return {pendiente:'Pendiente',descargando:'Descargando',completado:'Completado',error:'Con error'}[s]||s}
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.getElementById('page-'+p).classList.add('active');document.getElementById('pageTitle').textContent=pages[p][0];document.getElementById('pageSubtitle').textContent=pages[p][1];if(p==='dashboard')loadDashboard();if(p==='library')loadLibrary();if(p==='categories')loadCategories();if(p==='settings')loadSettings()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));

async function loadCategories(){CATEGORIES=await api('/api/categories');const sels=['rCategory','filterCategory','subCatParent'];for(const id of sels){const s=document.getElementById(id);const preserve=s.value;s.innerHTML=(id==='filterCategory'?'<option value="">Todas las categorías</option>':'')+CATEGORIES.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(preserve)s.value=preserve}updateSubcategorySelect();document.getElementById('categoryTree').innerHTML=CATEGORIES.map(c=>`<div class="cat-card"><strong>${esc(c.name)}</strong><div class="chips">${c.subcategories.length?c.subcategories.map(s=>`<span class="chip">${esc(s.name)}</span>`).join(''):'<span class="muted">Sin subcategorías</span>'}</div></div>`).join('')}
function updateSubcategorySelect(){const catId=Number(document.getElementById('rCategory').value);const cat=CATEGORIES.find(c=>c.id===catId);const s=document.getElementById('rSubcategory');s.innerHTML='<option value="">General</option>'+((cat?.subcategories||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''))}
document.getElementById('rCategory').addEventListener('change',updateSubcategorySelect);
async function createCategory(){const i=document.getElementById('newCategoryName');if(!i.value.trim())return;try{await api('/api/categories',{method:'POST',body:JSON.stringify({name:i.value.trim()})});i.value='';await loadCategories();toast('Categoría creada')}catch(e){toast(e.message)}}
async function createSubcategory(){const i=document.getElementById('newSubcategoryName'),cat=Number(document.getElementById('subCatParent').value);if(!i.value.trim()||!cat)return;try{await api('/api/subcategories',{method:'POST',body:JSON.stringify({category_id:cat,name:i.value.trim()})});i.value='';await loadCategories();toast('Subcategoría creada')}catch(e){toast(e.message)}}
async function quickSubcategory(){const cat=Number(document.getElementById('rCategory').value);if(!cat)return toast('Selecciona primero una categoría');const name=prompt('Nombre de la nueva subcategoría:');if(!name)return;try{await api('/api/subcategories',{method:'POST',body:JSON.stringify({category_id:cat,name:name.trim()})});await loadCategories();const c=CATEGORIES.find(c=>c.id===cat),s=c?.subcategories.find(s=>s.name.toLowerCase()===name.trim().toLowerCase());document.getElementById('rCategory').value=cat;updateSubcategorySelect();if(s)document.getElementById('rSubcategory').value=s.id;toast('Subcategoría creada')}catch(e){toast(e.message)}}

function resourcePayload(){return {name:document.getElementById('rName').value.trim(),url:document.getElementById('rUrl').value.trim(),category_id:Number(document.getElementById('rCategory').value),subcategory_id:document.getElementById('rSubcategory').value?Number(document.getElementById('rSubcategory').value):null}}
async function analyzeLink(){const p=resourcePayload();if(!p.url)return toast('Pega un enlace');if(!p.name)p.name='Sin nombre';try{const d=await api('/api/analyze',{method:'POST',body:JSON.stringify(p)});const b=document.getElementById('analyzeBox');b.classList.remove('hidden');b.innerHTML=d.existing?`⚠ Este enlace ya está registrado como <strong>${esc(d.existing.name)}</strong> (${statusLabel(d.existing.status)}).`:`✓ Enlace válido. Tipo detectado: <strong>${d.info.kind==='folder'?'Carpeta':'Archivo/enlace'}</strong>${d.info.id?` · ID: ${esc(d.info.id)}`:''}.`}catch(e){toast(e.message)}}
async function saveAndDownload(){const p=resourcePayload();if(!p.name||!p.url||!p.category_id)return toast('Completa nombre, enlace y categoría');try{const r=await api('/api/resources',{method:'POST',body:JSON.stringify(p)});await api(`/api/resources/${r.id}/download`,{method:'POST'});document.getElementById('rUrl').value='';document.getElementById('rName').value='';document.getElementById('analyzeBox').classList.add('hidden');toast('Recurso agregado. La descarga comenzó.');go('library')}catch(e){toast(e.message)}}

async function loadDashboard(){const s=await api('/api/stats');document.getElementById('stats').innerHTML=[['Recursos',s.resources],['Completados',s.completed],['En cola',s.pending],['Archivos',s.files],['Espacio',fmtBytes(s.bytes)]].map(([a,b])=>`<div class="stat"><b>${b}</b><span>${a}</span></div>`).join('');const rs=await api('/api/resources');document.getElementById('recentResources').innerHTML=renderResources(rs.slice(0,8),true)}
async function loadLibrary(){const q=encodeURIComponent(document.getElementById('searchQ').value||''),c=document.getElementById('filterCategory').value,s=document.getElementById('filterStatus').value;const rs=await api(`/api/resources?q=${q}&category_id=${c}&status=${encodeURIComponent(s)}`);document.getElementById('libraryList').innerHTML=renderResources(rs,false)}
function renderResources(rs,compact=false){if(!rs.length)return '<div class="empty">Todavía no hay recursos registrados.</div>';return rs.map(r=>`<div class="resource"><div><div class="resource-title">${esc(r.name)}</div><div class="resource-sub">${esc(r.category_name||'Sin categoría')} · ${esc(r.subcategory_name||'General')} · ${r.file_count||0} archivos · ${fmtBytes(r.total_bytes)}</div>${r.live?`<div class="progress"><i style="width:${r.live.progress||0}%"></i></div><div class="resource-sub">${esc(r.live.message||'')}</div>`:''}${r.error&&!r.live?`<div class="resource-sub" style="color:#b42318">${esc(r.error)}</div>`:''}</div><div class="resource-sub">${esc(r.url)}</div><div><span class="status s-${r.status}">${statusLabel(r.status)}</span></div><div class="res-actions">${r.status!=='descargando'?`<button class="icon-btn" title="${r.status==='completado'?'Actualizar descarga':'Descargar'}" onclick="download(${r.id})">↓</button>`:''}${r.local_path?`<button class="icon-btn" title="Abrir carpeta" onclick="openFolder(${r.id})">⌂</button><button class="icon-btn" title="Comprimir ZIP" onclick="zipResource(${r.id})">ZIP</button>`:''}<button class="icon-btn" title="Ver detalles" onclick="detail(${r.id})">⋯</button></div></div>`).join('')}
async function download(id){try{await api(`/api/resources/${id}/download`,{method:'POST'});toast('Descarga iniciada');setTimeout(loadLibrary,500)}catch(e){toast(e.message)}}
async function openFolder(id){try{await api(`/api/resources/${id}/open`,{method:'POST'})}catch(e){toast(e.message)}}
async function zipResource(id){try{const d=await api(`/api/resources/${id}/zip`,{method:'POST'});toast('ZIP creado en Exportaciones: '+d.path)}catch(e){toast(e.message)}}
async function rescan(id){try{const d=await api(`/api/resources/${id}/rescan`,{method:'POST'});toast(`Indexado: ${d.file_count} archivos`);detail(id)}catch(e){toast(e.message)}}
async function deleteResource(id){const delFiles=confirm('¿También deseas borrar los archivos descargados?\nAceptar = borrar registro y archivos.\nCancelar = solo borrar registro.');const sure=confirm(delFiles?'Se eliminará el registro y la carpeta local. ¿Continuar?':'Se eliminará solo el registro de la app. ¿Continuar?');if(!sure)return;try{await api(`/api/resources/${id}?delete_files=${delFiles?'true':'false'}`,{method:'DELETE'});closeModal();loadLibrary();toast('Recurso eliminado')}catch(e){toast(e.message)}}
async function detail(id){try{const r=await api(`/api/resources/${id}`);const types=(r.types||[]).map(t=>`<span class="type-pill"><b>${esc((t.ext||'').toUpperCase())}</b> · ${t.count} · ${fmtBytes(t.bytes)}</span>`).join('');const files=(r.files||[]).slice(0,100).map(f=>`<tr><td>${esc(f.rel_path)}</td><td>${esc((f.ext||'').toUpperCase())}</td><td>${fmtBytes(f.size_bytes)}</td></tr>`).join('');document.getElementById('modalContent').innerHTML=`<h2>${esc(r.name)}</h2><p class="muted">${esc(r.category_name||'')} / ${esc(r.subcategory_name||'General')}</p><div class="detail-grid"><div class="detail-box"><b>Estado</b><br><span class="status s-${r.status}">${statusLabel(r.status)}</span></div><div class="detail-box"><b>Contenido</b><br>${r.file_count} archivos · ${fmtBytes(r.total_bytes)}</div></div><h3>Tipos de archivo</h3><div class="type-grid">${types||'<span class="muted">Sin indexar</span>'}</div><div class="actions" style="justify-content:flex-start"><button class="secondary" onclick="openFolder(${r.id})">Abrir carpeta</button><button class="secondary" onclick="rescan(${r.id})">Reindexar</button><button class="secondary" onclick="zipResource(${r.id})">Crear ZIP</button><button class="danger" onclick="deleteResource(${r.id})">Eliminar</button></div><h3>Archivos <small class="muted">(máx. 100 visibles)</small></h3><table class="file-table"><thead><tr><th>Ruta</th><th>Tipo</th><th>Tamaño</th></tr></thead><tbody>${files||'<tr><td colspan="3">Sin archivos indexados.</td></tr>'}</tbody></table>`;document.getElementById('modal').classList.remove('hidden')}catch(e){toast(e.message)}}
function closeModal(){document.getElementById('modal').classList.add('hidden')}

async function loadSettings(){const c=await api('/api/config');document.getElementById('libraryPath').value=c.library_path;document.getElementById('configMeta').innerHTML=`Versión ${c.version}<br>Base de datos: ${esc(c.db_path)}`}
async function chooseLibraryFolder(){
  try{
    if(window.pywebview && window.pywebview.api && window.pywebview.api.choose_folder){
      const p=await window.pywebview.api.choose_folder();
      if(p)document.getElementById('libraryPath').value=p;
      return;
    }
    toast('El selector de carpetas está disponible en la aplicación instalada de Windows.');
  }catch(e){toast(e.message||'No se pudo abrir el selector de carpetas')}
}
async function saveSettings(){const p=document.getElementById('libraryPath').value.trim();if(!p)return;try{const d=await api('/api/config',{method:'PUT',body:JSON.stringify({library_path:p})});toast('Ubicación guardada: '+d.library_path);loadSettings()}catch(e){toast(e.message)}}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}

(async function init(){await loadCategories();await loadDashboard();setInterval(()=>{const active=document.querySelector('.page.active')?.id;if(active==='page-library')loadLibrary();if(active==='page-dashboard')loadDashboard()},2500)})().catch(e=>toast(e.message));
